/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 21 23:42:38 CEST 2014
 */

package evosuite;

import static org.junit.Assert.*;
import org.junit.Test;
import evosuite.Bubble;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException;
import org.evosuite.runtime.mock.java.lang.MockIllegalStateException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class Bubble_ESTest extends Bubble_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 evosuite.Bubble.add(II)I: I24 Branch 2 IFGE L15 - false
   */

  @Test
  public void test0()  throws Throwable  {
      Bubble bubble0 = new Bubble();
      try {
        int int0 = bubble0.add(0, (-1));
        fail("Expecting exception: MockIllegalStateException");
      
      } catch(MockIllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 evosuite.Bubble.add(II)I: I3 Branch 1 IFGE L12 - false
   */

  @Test
  public void test1()  throws Throwable  {
      Bubble bubble0 = new Bubble();
      try {
        int int0 = bubble0.add((-1276), (-1276));
        fail("Expecting exception: MockIllegalArgumentException");
      
      } catch(MockIllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 evosuite.Bubble.<init>()V: root-Branch
   * 2 evosuite.Bubble.add(II)I: I3 Branch 1 IFGE L12 - true
   * 3 evosuite.Bubble.add(II)I: I24 Branch 2 IFGE L15 - true
   */

  @Test
  public void test2()  throws Throwable  {
      Bubble bubble0 = new Bubble();
      int int0 = bubble0.add(0, 0);
      assertEquals(0, int0);
  }
}
